apiVersion: v1
kind: Service
metadata:
  labels:
    app: demoapp2
  name: demoapp-svc2
  namespace: auto-sync
spec:
  ports:
  - name: demoapp-ports
    nodePort: 31000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demoapp2
  type: NodePort
