apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demoapp2
  name: demoapp-dep2
  namespace: auto-sync
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demoapp2
  template:
    metadata:
      labels:
        app: demoapp2
    spec:
      containers:
      - image: thinknyx/demoapp:v1
        name: demoapp2
